#name: CI

#on:
  #push:
    #branches: [ master ]
  #pull_request:
    #branches: [ master ]

#jobs:
  #build:
    #runs-on: ubuntu-latest

    #steps:
      #- uses: actions/checkout@v2
        #env:
          #ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}' 
          #github_token: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}' 
          #ado_organization: '${{ secrets.ADO_ORGANIZATION }}'
          #ado_project: '${{ secrets.ADO_PROJECT }}'
          #ado_wit: 'Pull Request' 
          #ado_new_state: 'New'
          #ado_active_state: 'Active'
          #ado_close_state: 'Closed'
